[workspace]
members = [
    "apps/fabric-cli",
    "crates/fabric-core",
]
default-members = ["apps/fabric-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

