name: verify

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  posix:
    name: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-26
          - macos-26-intel
          - ubuntu-24.04-arm
          - ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - run: sh scripts/setup.sh

  windows:
    name: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-11-vs2026-arm
          - windows-2025-vs2026
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - shell: pwsh
        run: ./scripts/setup.ps1
